import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { Sparkles, Save, Loader2, Target } from "lucide-react";
import type { Department } from "@shared/schema";

const INDUSTRIES = [
  "Hospitality", "Restaurants", "Retail", "Real Estate", "Healthcare clinics",
  "Trading companies", "Maintenance / field services", "Professional services",
  "Offshore Helicopter company"
];

export default function KpiBuilderPage() {
  const { toast } = useToast();
  const { data: company } = useQuery<any>({ queryKey: ["/api/company"] });
  const { data: departments } = useQuery<Department[]>({ queryKey: ["/api/departments"] });

  const [industry, setIndustry] = useState("");
  const [department, setDepartment] = useState("");
  const [goals, setGoals] = useState("");
  const [generatedKpis, setGeneratedKpis] = useState<any[]>([]);

  const generateMutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest("POST", "/api/ai/generate-kpis", {
        industry: industry || company?.industry,
        department,
        goals: goals.split(",").map((g: string) => g.trim()).filter(Boolean),
      });
      return res.json();
    },
    onSuccess: (data) => {
      setGeneratedKpis(data);
      toast({ title: "KPIs Generated", description: `${data.length} KPIs generated by AI` });
    },
    onError: (err: any) => {
      toast({ title: "Error", description: err.message, variant: "destructive" });
    },
  });

  const saveMutation = useMutation({
    mutationFn: async (kpi: any) => {
      const deptObj = departments?.find(d => d.name === department);
      await apiRequest("POST", "/api/kpis", {
        departmentId: deptObj?.id || null,
        kpiName: kpi.kpi_name,
        description: kpi.description,
        formula: kpi.formula,
        unit: kpi.unit,
        frequency: kpi.frequency,
        targetValue: kpi.target_value,
        greenThreshold: kpi.green_threshold,
        amberThreshold: kpi.amber_threshold,
        redThreshold: kpi.red_threshold,
        ownerName: kpi.owner_name,
        dataSource: kpi.data_source,
        createdByAi: true,
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/kpis"] });
      toast({ title: "Saved", description: "KPI saved successfully" });
    },
  });

  return (
    <div className="p-6 space-y-6">
      <div>
        <h1 className="text-2xl font-bold" data-testid="text-kpi-builder-title">KPI Builder</h1>
        <p className="text-muted-foreground">Generate AI-powered KPIs tailored to your business</p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="text-base flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-primary" />
            Generate KPIs
          </CardTitle>
          <CardDescription>Select your industry, department, and goals to generate relevant KPIs</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="space-y-2">
              <Label>Industry</Label>
              <Select value={industry || company?.industry || ""} onValueChange={setIndustry}>
                <SelectTrigger data-testid="select-kpi-industry"><SelectValue placeholder="Select industry" /></SelectTrigger>
                <SelectContent>
                  {INDUSTRIES.map(i => <SelectItem key={i} value={i}>{i}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>Department</Label>
              <Select value={department} onValueChange={setDepartment}>
                <SelectTrigger data-testid="select-kpi-department"><SelectValue placeholder="Select department" /></SelectTrigger>
                <SelectContent>
                  {(departments || []).map(d => <SelectItem key={d.id} value={d.name}>{d.name}</SelectItem>)}
                  {["Sales", "Finance", "HR", "Operations", "Procurement", "Customer Service", "Marketing"]
                    .filter(n => !(departments || []).some(d => d.name === n))
                    .map(n => <SelectItem key={n} value={n}>{n}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>Business Priorities</Label>
              <Input value={goals} onChange={(e) => setGoals(e.target.value)} placeholder="e.g. Increase revenue, Reduce costs" data-testid="input-kpi-goals" />
            </div>
          </div>
          <Button onClick={() => generateMutation.mutate()} disabled={generateMutation.isPending || !department} data-testid="button-generate-kpis">
            {generateMutation.isPending ? <><Loader2 className="h-4 w-4 mr-2 animate-spin" />Generating...</> : <><Sparkles className="h-4 w-4 mr-2" />Generate KPIs</>}
          </Button>
        </CardContent>
      </Card>

      {generatedKpis.length > 0 && (
        <div className="space-y-4">
          <h2 className="text-lg font-semibold" data-testid="text-generated-count">Generated KPIs ({generatedKpis.length})</h2>
          <div className="grid gap-4">
            {generatedKpis.map((kpi, i) => (
              <Card key={i}>
                <CardContent className="p-4">
                  <div className="flex items-start justify-between gap-4">
                    <div className="flex-1 space-y-2">
                      <div className="flex items-center gap-2 flex-wrap">
                        <Target className="h-4 w-4 text-primary" />
                        <h3 className="font-semibold" data-testid={`text-kpi-name-${i}`}>{kpi.kpi_name}</h3>
                        <Badge variant="secondary">{kpi.frequency}</Badge>
                        <Badge variant="secondary">{kpi.unit}</Badge>
                      </div>
                      <p className="text-sm text-muted-foreground">{kpi.description}</p>
                      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 mt-3">
                        <div>
                          <p className="text-xs text-muted-foreground">Formula</p>
                          <p className="text-sm font-mono">{kpi.formula}</p>
                        </div>
                        <div>
                          <p className="text-xs text-muted-foreground">Target</p>
                          <p className="text-sm font-medium">{kpi.target_value}</p>
                        </div>
                        <div>
                          <p className="text-xs text-muted-foreground">Owner</p>
                          <p className="text-sm">{kpi.owner_name}</p>
                        </div>
                        <div>
                          <p className="text-xs text-muted-foreground">Data Source</p>
                          <p className="text-sm">{kpi.data_source}</p>
                        </div>
                      </div>
                      <div className="flex gap-2 mt-2 flex-wrap">
                        <Badge variant="default" className="text-xs">Green: {kpi.green_threshold}</Badge>
                        <Badge variant="secondary" className="text-xs">Amber: {kpi.amber_threshold}</Badge>
                        <Badge variant="destructive" className="text-xs">Red: {kpi.red_threshold}</Badge>
                      </div>
                    </div>
                    <Button size="sm" onClick={() => saveMutation.mutate(kpi)} disabled={saveMutation.isPending} data-testid={`button-save-kpi-${i}`}>
                      <Save className="h-4 w-4 mr-1" />Save
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
